version: 3

vars:
  ENV_LOCAL_FILE: .env.local

tasks:
  init:
    cmds:
      - cmd: cp .env.example {{.ENV_LOCAL_FILE}}
        if: "[ ! -f {{.ENV_LOCAL_FILE}} ]"

  up:
    preconditions:
      - sh: command -v docker >/dev/null 2>&1
        msg: Docker is not installed.
      - sh: command -v go >/dev/null 2>&1
        msg: Go is not installed.
    cmds:
      - task: init
      - go mod tidy
      - docker compose --env-file {{.ENV_LOCAL_FILE}} up --build

  down:
    cmds:
      - docker compose --env-file {{.ENV_LOCAL_FILE}} down
